// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rURT7PSYpAQNuaCGHJDPZg
// Component: 5zjokN2A33jNz

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Header from "../../Header"; // plasmic-import: 8weNktnDWmJHK/component
import { Reveal } from "@plasmicpkgs/react-awesome-reveal";
import Footer from "../../Footer"; // plasmic-import: VnNBHcpuRiqHc/component

import { useScreenVariants as useScreenVariantshCgzN1EtzMdy } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: hCGZ-N1etzMDY/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_w_3_hc_web.module.css"; // plasmic-import: rURT7PSYpAQNuaCGHJDPZg/projectcss
import sty from "./PlasmicSoon.module.css"; // plasmic-import: 5zjokN2A33jNz/css

createPlasmicElementProxy;

export type PlasmicSoon__VariantMembers = {};
export type PlasmicSoon__VariantsArgs = {};
type VariantPropType = keyof PlasmicSoon__VariantsArgs;
export const PlasmicSoon__VariantProps = new Array<VariantPropType>();

export type PlasmicSoon__ArgsType = {};
type ArgPropType = keyof PlasmicSoon__ArgsType;
export const PlasmicSoon__ArgProps = new Array<ArgPropType>();

export type PlasmicSoon__OverridesType = {
  root?: Flex__<"div">;
  header?: Flex__<typeof Header>;
  text?: Flex__<"div">;
  ul?: Flex__<"ul">;
  footer?: Flex__<typeof Footer>;
};

export interface DefaultSoonProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSoon__RenderFunc(props: {
  variants: PlasmicSoon__VariantsArgs;
  args: PlasmicSoon__ArgsType;
  overrides: PlasmicSoon__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantshCgzN1EtzMdy()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />
        <title key="title">{PlasmicSoon.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicSoon.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicSoon.pageMetadata.title}
        />
        <meta
          key="description"
          name="description"
          content={PlasmicSoon.pageMetadata.description}
        />
        <meta
          key="og:description"
          property="og:description"
          content={PlasmicSoon.pageMetadata.description}
        />
        <meta
          key="twitter:description"
          name="twitter:description"
          content={PlasmicSoon.pageMetadata.description}
        />
        <meta
          key="og:image"
          property="og:image"
          content={PlasmicSoon.pageMetadata.ogImageSrc}
        />
        <meta
          key="twitter:image"
          name="twitter:image"
          content={PlasmicSoon.pageMetadata.ogImageSrc}
        />
        <link ref="canonical" href={PlasmicSoon.pageMetadata.canonical} />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <div className={classNames(projectcss.all, sty.freeBox__lPHaW)}>
            <div className={classNames(projectcss.all, sty.freeBox__nCqub)}>
              <Reveal
                className={classNames("__wab_instance", sty.reveal__d2EAq)}
                duration={10000}
                triggerOnce={true}
              >
                <div
                  data-plasmic-name={"text"}
                  data-plasmic-override={overrides.text}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text
                  )}
                >
                  {"Soon"}
                </div>
              </Reveal>
            </div>
            <Reveal
              cascade={false}
              className={classNames("__wab_instance", sty.reveal__rkHrK)}
              delay={5000}
              direction={"left"}
              duration={2000}
              effect={"zoom"}
              triggerOnce={false}
            >
              <PlasmicLink__
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link__wy0Z1
                )}
                component={Link}
                href={"https://github.com/w3hc"}
                platform={"nextjs"}
                target={"_blank"}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly") ? (
                  <React.Fragment>
                    <React.Fragment>
                      {
                        "The Web3 Hackers Collective is a DAO created on February 24, 2023. It is deployed to Optimism Mainnet. We're using "
                      }
                    </React.Fragment>
                    {
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          projectcss.plasmic_default__inline,
                          sty.link__fpkwF
                        )}
                        component={Link}
                        href={"https://github.com/w3hc/gov"}
                        platform={"nextjs"}
                        target={"_blank"}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "Gov"
                          : "Gov"}
                      </PlasmicLink__>
                    }
                    <React.Fragment>
                      {
                        " which is an implementation of Open Zeppelin's Governor contract in combination with NFTs. \n\nOur mission statement is:\n\n "
                      }
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {
                        '"We want to build integrations through mentoring and learning."'
                      }
                    </span>
                    <React.Fragment>
                      {
                        "\n\nAny proposal should meet one of the following criteria:\n\n"
                      }
                    </React.Fragment>
                    {
                      <ul
                        data-plasmic-name={"ul"}
                        data-plasmic-override={overrides.ul}
                        className={classNames(
                          projectcss.all,
                          projectcss.ul,
                          sty.ul
                        )}
                      >
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__xtUm4
                          )}
                        >
                          {hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "Organize local hackathons, workshops and meetups"
                            : "Organize local hackathons, workshops and meetups"}
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__eqZeu
                          )}
                        >
                          {hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "Request retroactive funding for a successful integration"
                            : "Request retroactive funding for a successful integration"}
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__gkNP
                          )}
                        >
                          {hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "Develop and maintain Gov: a DAO framework built with Governor and NFTs"
                            : "Develop and maintain Gov: a DAO framework built with Governor and NFTs"}
                        </li>
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__lMlwn
                          )}
                        >
                          {hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "Help people to setup their own DAO"
                            : "Help people to setup their own DAO"}
                        </li>
                      </ul>
                    }
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                ) : (
                  "Have a look at the W3HC on Github"
                )}
              </PlasmicLink__>
            </Reveal>
          </div>
          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "header", "text", "ul", "footer"],
  header: ["header"],
  text: ["text"],
  ul: ["ul"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: typeof Header;
  text: "div";
  ul: "ul";
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSoon__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSoon__VariantsArgs;
    args?: PlasmicSoon__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicSoon__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicSoon__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSoon__ArgProps,
          internalVariantPropNames: PlasmicSoon__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSoon__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSoon";
  } else {
    func.displayName = `PlasmicSoon.${nodeName}`;
  }
  return func;
}

export const PlasmicSoon = Object.assign(
  // Top-level PlasmicSoon renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    text: makeNodeComponent("text"),
    ul: makeNodeComponent("ul"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicSoon
    internalVariantProps: PlasmicSoon__VariantProps,
    internalArgProps: PlasmicSoon__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "W3HC - Projects",
      description:
        "We want to build integrations through mentoring and learning.",
      ogImageSrc:
        "https://site-assets.plasmic.app/16913ee9842ff1d4b5c32ddeb18c5be8.png",
      canonical: "https://w3hc.org/projects"
    }
  }
);

export default PlasmicSoon;
/* prettier-ignore-end */
