// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rURT7PSYpAQNuaCGHJDPZg
// Component: U9_ketn8GVz

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Header from "../../Header"; // plasmic-import: 8weNktnDWmJHK/component
import Footer from "../../Footer"; // plasmic-import: VnNBHcpuRiqHc/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_w_3_hc_web.module.css"; // plasmic-import: rURT7PSYpAQNuaCGHJDPZg/projectcss
import sty from "./PlasmicProjects.module.css"; // plasmic-import: U9_ketn8GVz/css

createPlasmicElementProxy;

export type PlasmicProjects__VariantMembers = {};
export type PlasmicProjects__VariantsArgs = {};
type VariantPropType = keyof PlasmicProjects__VariantsArgs;
export const PlasmicProjects__VariantProps = new Array<VariantPropType>();

export type PlasmicProjects__ArgsType = {};
type ArgPropType = keyof PlasmicProjects__ArgsType;
export const PlasmicProjects__ArgProps = new Array<ArgPropType>();

export type PlasmicProjects__OverridesType = {
  root?: Flex__<"div">;
  header?: Flex__<typeof Header>;
  block4?: Flex__<"div">;
  block5?: Flex__<"div">;
  block6?: Flex__<"div">;
  block?: Flex__<"div">;
  block2?: Flex__<"div">;
  block8?: Flex__<"div">;
  block3?: Flex__<"div">;
  block7?: Flex__<"div">;
  block9?: Flex__<"div">;
  block10?: Flex__<"div">;
  block11?: Flex__<"div">;
  footer?: Flex__<typeof Footer>;
};

export interface DefaultProjectsProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicProjects__RenderFunc(props: {
  variants: PlasmicProjects__VariantsArgs;
  args: PlasmicProjects__ArgsType;
  overrides: PlasmicProjects__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />
        <title key="title">{PlasmicProjects.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicProjects.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicProjects.pageMetadata.title}
        />
        <meta
          key="description"
          name="description"
          content={PlasmicProjects.pageMetadata.description}
        />
        <meta
          key="og:description"
          property="og:description"
          content={PlasmicProjects.pageMetadata.description}
        />
        <meta
          key="twitter:description"
          name="twitter:description"
          content={PlasmicProjects.pageMetadata.description}
        />
        <meta
          key="og:image"
          property="og:image"
          content={PlasmicProjects.pageMetadata.ogImageSrc}
        />
        <meta
          key="twitter:image"
          name="twitter:image"
          content={PlasmicProjects.pageMetadata.ogImageSrc}
        />
        <link ref="canonical" href={PlasmicProjects.pageMetadata.canonical} />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <div className={classNames(projectcss.all, sty.freeBox__je67)}>
            <div className={classNames(projectcss.all, sty.freeBox__oGkwK)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__fby3J
                )}
              >
                <React.Fragment>
                  <React.Fragment>{'Our mission is to "'}</React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontWeight: 700 }}
                  >
                    {"build integrations through mentoring and education"}
                  </span>
                  <React.Fragment>
                    {
                      "\". So wherever it's relevant, we would integrate with existing Web3 apps, tools, protocols and networks, which gives us the opportunity to train apprentice hackers: mutual aid is something we value a lot. \n\nWe try to be a bit strict when it comes to open source project development best practices. We believe that's the only way to build a healthy and strong Web3 ecosystem. Standardization is essential.\n\nYou're invited to "
                    }
                  </React.Fragment>
                  {
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        projectcss.plasmic_default__inline,
                        sty.link__vdTrM
                      )}
                      component={Link}
                      href={"https://discord.com/invite/uSxzJp3J76"}
                      platform={"nextjs"}
                      target={"_blank"}
                    >
                      {"join us in Discord"}
                    </PlasmicLink__>
                  }
                  <React.Fragment>{" or "}</React.Fragment>
                  {
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        projectcss.plasmic_default__inline,
                        sty.link__vhN0E
                      )}
                      component={Link}
                      href={"https://t.me/+5ih-ivs0VVM0NWU0"}
                      platform={"nextjs"}
                      target={"_blank"}
                    >
                      {"Telegram"}
                    </PlasmicLink__>
                  }
                  <React.Fragment>{", "}</React.Fragment>
                  {
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        projectcss.plasmic_default__inline,
                        sty.link__gdqgb
                      )}
                      component={Link}
                      href={"https://forms.gle/MYAfygPm5GD95HQ19"}
                      platform={"nextjs"}
                    >
                      {"apply to become a member of the DAO"}
                    </PlasmicLink__>
                  }
                  <React.Fragment>
                    {
                      " if you feel like you're motivated and want to learn, or "
                    }
                  </React.Fragment>
                  {
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        projectcss.plasmic_default__inline,
                        sty.link__rtDBg
                      )}
                      component={Link}
                      href={"https://github.com/w3hc"}
                      platform={"nextjs"}
                    >
                      {"contribute directly via Github"}
                    </PlasmicLink__>
                  }
                  <React.Fragment>{"."}</React.Fragment>
                </React.Fragment>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__rd4Fe
                )}
              >
                {"Integrations"}
              </div>
              <div
                data-plasmic-name={"block4"}
                data-plasmic-override={overrides.block4}
                className={classNames(projectcss.all, sty.block4)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__kWyHr
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          projectcss.plasmic_default__inline,
                          sty.link__iNjKc
                        )}
                        component={Link}
                        href={`/soon`}
                        platform={"nextjs"}
                      >
                        {"Medusa <> Gov"}
                      </PlasmicLink__>
                    }
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
              </div>
              <div
                data-plasmic-name={"block5"}
                data-plasmic-override={overrides.block5}
                className={classNames(projectcss.all, sty.block5)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___912C4
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          projectcss.plasmic_default__inline,
                          sty.link___2U90Z
                        )}
                        component={Link}
                        href={`/soon`}
                        platform={"nextjs"}
                      >
                        {"Lens <> Celo"}
                      </PlasmicLink__>
                    }
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
              </div>
              <div
                data-plasmic-name={"block6"}
                data-plasmic-override={overrides.block6}
                className={classNames(projectcss.all, sty.block6)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___1Xk72
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          projectcss.plasmic_default__inline,
                          sty.link___3YrLu
                        )}
                        component={Link}
                        href={`/soon`}
                        platform={"nextjs"}
                      >
                        {"Superfluid <> FEVM"}
                      </PlasmicLink__>
                    }
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___0CYdq
                )}
              >
                {"In-house projects"}
              </div>
              <div
                data-plasmic-name={"block"}
                data-plasmic-override={overrides.block}
                className={classNames(projectcss.all, sty.block)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ojCyE
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          projectcss.plasmic_default__inline,
                          sty.link__ythbV
                        )}
                        component={Link}
                        href={"https://github.com/w3hc/gov"}
                        platform={"nextjs"}
                        target={"_blank"}
                      >
                        {"Gov"}
                      </PlasmicLink__>
                    }
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___6EsYu
                  )}
                >
                  {
                    "Gov is a DAO framework built with Open Zeppelin\u2019s Governor contract in combination with NFTs. It provides a coordination tool that fits the needs of everyday people."
                  }
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__yZyB
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          projectcss.plasmic_default__inline,
                          sty.link__ushDq
                        )}
                        component={Link}
                        href={"https://github.com/w3hc/gov"}
                        platform={"nextjs"}
                        target={"_blank"}
                      >
                        {"Github repo"}
                      </PlasmicLink__>
                    }
                    <React.Fragment>{" | "}</React.Fragment>
                    {
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          projectcss.plasmic_default__inline,
                          sty.link__qIbvb
                        )}
                        component={Link}
                        href={"https://github.com/orgs/w3hc/projects/8/views/6"}
                        platform={"nextjs"}
                        target={"_blank"}
                      >
                        {"Task board"}
                      </PlasmicLink__>
                    }
                    <React.Fragment>{" | "}</React.Fragment>
                    {
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          projectcss.plasmic_default__inline,
                          sty.link__rJu5Z
                        )}
                        component={Link}
                        href={"https://w3hc.github.io/gov-docs/"}
                        platform={"nextjs"}
                      >
                        <React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ color: "var(--token-zqwdlV4ZdEYm_k)" }}
                          >
                            {"Docs"}
                          </span>
                        </React.Fragment>
                      </PlasmicLink__>
                    }
                    <React.Fragment>{""}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "var(--token-u_cGwS23As82q0)" }}
                    >
                      {" | "}
                    </span>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          projectcss.plasmic_default__inline,
                          sty.link___8UXMj
                        )}
                        component={Link}
                        href={"https://gov-ui.netlify.app/"}
                        platform={"nextjs"}
                      >
                        <React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ color: "var(--token-zqwdlV4ZdEYm_k)" }}
                          >
                            {"Live demo"}
                          </span>
                        </React.Fragment>
                      </PlasmicLink__>
                    }
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
              </div>
              <div
                data-plasmic-name={"block2"}
                data-plasmic-override={overrides.block2}
                className={classNames(projectcss.all, sty.block2)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ymgWl
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          projectcss.plasmic_default__inline,
                          sty.link__sLgJt
                        )}
                        component={Link}
                        href={"https://github.com/w3hc/gcfa-contracts"}
                        platform={"nextjs"}
                        target={"_blank"}
                      >
                        {"Pattini"}
                      </PlasmicLink__>
                    }
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__kopEd
                  )}
                >
                  {
                    "Pattini is a GitHub Action designed to incentivize and reward contributors of a GitHub project. When an issue is merged by a maintainer, the pull request author automatically receives a certain amount of ERC-20 (USDC, DAI, ...)."
                  }
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__u12Ys
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          projectcss.plasmic_default__inline,
                          sty.link__f0KkU
                        )}
                        component={Link}
                        href={"https://github.com/w3hc/pattini"}
                        platform={"nextjs"}
                        target={"_blank"}
                      >
                        {"Github repo"}
                      </PlasmicLink__>
                    }
                    <React.Fragment>{" | "}</React.Fragment>
                    {
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          projectcss.plasmic_default__inline,
                          sty.link__sjpWl
                        )}
                        component={Link}
                        href={"https://github.com/orgs/w3hc/projects/17"}
                        platform={"nextjs"}
                        target={"_blank"}
                      >
                        {"Task board"}
                      </PlasmicLink__>
                    }
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
              </div>
              <div
                data-plasmic-name={"block8"}
                data-plasmic-override={overrides.block8}
                className={classNames(projectcss.all, sty.block8)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__gMIaW
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          projectcss.plasmic_default__inline,
                          sty.link___63Y9
                        )}
                        component={Link}
                        href={`/projects`}
                        platform={"nextjs"}
                      >
                        {"Web3 DD"}
                      </PlasmicLink__>
                    }
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__m6EJe
                  )}
                >
                  {
                    "A classic file explorer to manage your files and directories in a safe and decentralized fashion."
                  }
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__rgQor
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          projectcss.plasmic_default__inline,
                          sty.link__uBkmf
                        )}
                        component={Link}
                        href={"https://github.com/w3hc/web3dd"}
                        platform={"nextjs"}
                      >
                        {"Github repo"}
                      </PlasmicLink__>
                    }
                    <React.Fragment>{" | "}</React.Fragment>
                    {
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          projectcss.plasmic_default__inline,
                          sty.link__j3Lgh
                        )}
                        component={Link}
                        href={`/projects`}
                        platform={"nextjs"}
                      >
                        {"Task board"}
                      </PlasmicLink__>
                    }
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__f5JW2
                )}
              >
                {"Hackathons"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__t3Ha
                )}
              >
                {"Integrations"}
              </div>
              <div
                data-plasmic-name={"block3"}
                data-plasmic-override={overrides.block3}
                className={classNames(projectcss.all, sty.block3)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xnsKq
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          projectcss.plasmic_default__inline,
                          sty.link___9Pu8C
                        )}
                        component={Link}
                        href={"https://github.com/w3hc/uniswap-v3-deploy"}
                        platform={"nextjs"}
                        target={"_blank"}
                      >
                        {"Uniswap V3 Deploy"}
                      </PlasmicLink__>
                    }
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ztSCg
                  )}
                >
                  {
                    "This package includes a CLI script for deploying the latest Uniswap V3 smart contracts to any EVM (Ethereum Virtual Machine) compatible network."
                  }
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___6DQrq
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          projectcss.plasmic_default__inline,
                          sty.link__oBecx
                        )}
                        component={Link}
                        href={"https://github.com/w3hc/uniswap-v3-deploy"}
                        platform={"nextjs"}
                        target={"_blank"}
                      >
                        {"Github repo"}
                      </PlasmicLink__>
                    }
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
              </div>
              <div
                data-plasmic-name={"block7"}
                data-plasmic-override={overrides.block7}
                className={classNames(projectcss.all, sty.block7)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__amXpU
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          projectcss.plasmic_default__inline,
                          sty.link__e9NDh
                        )}
                        component={Link}
                        href={"https://github.com/w3hc/uniswap-v3-deploy"}
                        platform={"nextjs"}
                        target={"_blank"}
                      >
                        {"Portable Profile"}
                      </PlasmicLink__>
                    }
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__gHu0T
                  )}
                >
                  {
                    "This package includes a CLI script for deploying the latest Uniswap V3 smart contracts to any EVM (Ethereum Virtual Machine) compatible network."
                  }
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__v6Pr
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          projectcss.plasmic_default__inline,
                          sty.link__gs2Y4
                        )}
                        component={Link}
                        href={"https://portableprofile.app/"}
                        platform={"nextjs"}
                        target={"_blank"}
                      >
                        {"Project description"}
                      </PlasmicLink__>
                    }
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__uehlp
                )}
              >
                {"Templates"}
              </div>
              <div
                data-plasmic-name={"block9"}
                data-plasmic-override={overrides.block9}
                className={classNames(projectcss.all, sty.block9)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___46B6J
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          projectcss.plasmic_default__inline,
                          sty.link__ysnIv
                        )}
                        component={Link}
                        href={"https://github.com/w3hc/gcfa-contracts"}
                        platform={"nextjs"}
                        target={"_blank"}
                      >
                        {"Hardhat Template"}
                      </PlasmicLink__>
                    }
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__kKgLu
                  )}
                >
                  {
                    "A Hardhat template that includes Typescript, Ethers v6, OpenZeppelin Contracts v5.0.1, Hardhat Verify plugin, and Hardhat Deploy plugin"
                  }
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__i7NFa
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          projectcss.plasmic_default__inline,
                          sty.link__dYgry
                        )}
                        component={Link}
                        href={"https://github.com/w3hc/w3hc-hardhat-template"}
                        platform={"nextjs"}
                        target={"_blank"}
                      >
                        {"Github repo"}
                      </PlasmicLink__>
                    }
                    <React.Fragment> </React.Fragment>
                    {
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          projectcss.plasmic_default__inline,
                          sty.link___5THy
                        )}
                        component={Link}
                        href={"https://github.com/orgs/w3hc/projects/17"}
                        platform={"nextjs"}
                        target={"_blank"}
                      >
                        {"                             "}
                      </PlasmicLink__>
                    }
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
              </div>
              <div
                data-plasmic-name={"block10"}
                data-plasmic-override={overrides.block10}
                className={classNames(projectcss.all, sty.block10)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__qUfB
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          projectcss.plasmic_default__inline,
                          sty.link___44JzU
                        )}
                        component={Link}
                        href={"https://github.com/w3hc/gcfa-contracts"}
                        platform={"nextjs"}
                        target={"_blank"}
                      >
                        {"Genji - Next.js template"}
                      </PlasmicLink__>
                    }
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___3EYjo
                  )}
                >
                  {
                    "A Next.js Web3 app template that includes Web3 Modal, email login, Ethers.js (v6), and Chakra UI."
                  }
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__o4T45
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          projectcss.plasmic_default__inline,
                          sty.link__n1N5H
                        )}
                        component={Link}
                        href={"https://github.com/w3hc/genji"}
                        platform={"nextjs"}
                        target={"_blank"}
                      >
                        {"Github repo"}
                      </PlasmicLink__>
                    }
                    <React.Fragment> </React.Fragment>
                    {
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          projectcss.plasmic_default__inline,
                          sty.link__d4VaJ
                        )}
                        component={Link}
                        href={"https://github.com/orgs/w3hc/projects/17"}
                        platform={"nextjs"}
                        target={"_blank"}
                      >
                        {"                             "}
                      </PlasmicLink__>
                    }
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
              </div>
              <div
                data-plasmic-name={"block11"}
                data-plasmic-override={overrides.block11}
                className={classNames(projectcss.all, sty.block11)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__q7CJ6
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          projectcss.plasmic_default__inline,
                          sty.link__ugx2
                        )}
                        component={Link}
                        href={"https://github.com/w3hc/gcfa-contracts"}
                        platform={"nextjs"}
                        target={"_blank"}
                      >
                        {"Nest.js API Template"}
                      </PlasmicLink__>
                    }
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__dhAye
                  )}
                >
                  {"Nestjs-based API that uses PostgreSQL and Ethersjs."}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fgkz
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          projectcss.plasmic_default__inline,
                          sty.link__cgV2H
                        )}
                        component={Link}
                        href={"https://github.com/w3hc/web3-nestjs"}
                        platform={"nextjs"}
                        target={"_blank"}
                      >
                        {"Github repo"}
                      </PlasmicLink__>
                    }
                    <React.Fragment>{"  "}</React.Fragment>
                    {
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          projectcss.plasmic_default__inline,
                          sty.link__batW
                        )}
                        component={Link}
                        href={"https://github.com/orgs/w3hc/projects/17"}
                        platform={"nextjs"}
                        target={"_blank"}
                      >
                        {"              "}
                      </PlasmicLink__>
                    }
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
              </div>
            </div>
          </div>
          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "block4",
    "block5",
    "block6",
    "block",
    "block2",
    "block8",
    "block3",
    "block7",
    "block9",
    "block10",
    "block11",
    "footer"
  ],
  header: ["header"],
  block4: ["block4"],
  block5: ["block5"],
  block6: ["block6"],
  block: ["block"],
  block2: ["block2"],
  block8: ["block8"],
  block3: ["block3"],
  block7: ["block7"],
  block9: ["block9"],
  block10: ["block10"],
  block11: ["block11"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: typeof Header;
  block4: "div";
  block5: "div";
  block6: "div";
  block: "div";
  block2: "div";
  block8: "div";
  block3: "div";
  block7: "div";
  block9: "div";
  block10: "div";
  block11: "div";
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicProjects__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicProjects__VariantsArgs;
    args?: PlasmicProjects__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicProjects__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicProjects__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicProjects__ArgProps,
          internalVariantPropNames: PlasmicProjects__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicProjects__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicProjects";
  } else {
    func.displayName = `PlasmicProjects.${nodeName}`;
  }
  return func;
}

export const PlasmicProjects = Object.assign(
  // Top-level PlasmicProjects renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    block4: makeNodeComponent("block4"),
    block5: makeNodeComponent("block5"),
    block6: makeNodeComponent("block6"),
    block: makeNodeComponent("block"),
    block2: makeNodeComponent("block2"),
    block8: makeNodeComponent("block8"),
    block3: makeNodeComponent("block3"),
    block7: makeNodeComponent("block7"),
    block9: makeNodeComponent("block9"),
    block10: makeNodeComponent("block10"),
    block11: makeNodeComponent("block11"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicProjects
    internalVariantProps: PlasmicProjects__VariantProps,
    internalArgProps: PlasmicProjects__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "W3HC - Projects",
      description:
        "We want to build integrations through mentoring and learning.",
      ogImageSrc:
        "https://site-assets.plasmic.app/16913ee9842ff1d4b5c32ddeb18c5be8.png",
      canonical: "https://w3hc.org/projects"
    }
  }
);

export default PlasmicProjects;
/* prettier-ignore-end */
